= Social Engineering
Harishbabu Rengaraj

== What is it ?

* Type of Cyberattack accomplished through human interactions.
* Which involves **psychological manipulation** to trick users into making security mistakes or giving away sensitive information.
* The attacker tends to motivate the user into compromising themselves, rather than using brute force methods to breach your data.
* No one is immune: Many smart and careful people can fall victim to a social.
engineering attack without even realizing it until it is too late.

== Motive
- **Theft**, Obtaining valuables like information, access, or money.
- **Sabotage**, Disrupting or corrupting data to cause harm. 

== How it happens ?
Attacker's use of precaution and confidence.
- Emotion Manipulation : Triggering Fear, Excitement, Curiosity, Anger, and Guilt.
- Urgency
- Trust

== Types of Attack 
[options="header",width="50%",align="center"]
|====
| Attack  | Description
| Phishing	    | Most common phishing technique, which we all experienced atleast once.
| ROW 2	    | ROW 2
|====

== Two Column Demo

=== Right

[source,c]
------
#include <stdio.h>

int main()
{
	printf("Hello World\n");
	return 0;
}
------

=== Left

  * BULLET-1
  * BULLET-2
  * BULLET-3
  * BULLET-4

